name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Deps
        run: npm ci

      - name: Build
        run: npm run build

      - uses: pyTooling/Actions/releaser@r0
        with:
          files: ./bin/*.js
          rm: true
          tag: latest
          token: ${{ secrets.GITHUB_TOKEN }}
